<<<<<<< HEAD
spring.datasource.url=jdbc:mysql://localhost:3306/studentcrud
spring.datasource.username=root
spring.datasource.password=Dec19@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======
spring.application.name=Sum-calculator
server.port=8081
>>>>>>> 30b7081bc035c75789b2aab2c810551c704c90de
